// <auto-generated />
using System;
using GastroPro.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GastroPro.Infrastructure.Migrations
{
    [DbContext(typeof(GastroProDbContext))]
    [Migration("20260527163637_GastroPro_V1_Base")]
    partial class GastroPro_V1_Base
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GastroPro.Domain.Entities.CierreCaja", b =>
                {
                    b.Property<int>("CierreCajaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CierreCajaId"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalVendido")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("CierreCajaId");

                    b.ToTable("CierresCaja");
                });

            modelBuilder.Entity("GastroPro.Domain.Entities.Pago", b =>
                {
                    b.Property<int>("PagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PagoId"));

                    b.Property<int>("CierreCajaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NroOperacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroMesa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPagado")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PagoId");

                    b.HasIndex("CierreCajaId");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("GastroPro.Domain.Entities.Pedido", b =>
                {
                    b.Property<int>("PedidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PedidoId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroMesa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlatoId")
                        .HasColumnType("int");

                    b.HasKey("PedidoId");

                    b.HasIndex("PlatoId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("GastroPro.Domain.Entities.Plato", b =>
                {
                    b.Property<int>("PlatoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlatoId"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PlatoId");

                    b.ToTable("Platos");

                    b.HasData(
                        new
                        {
                            PlatoId = 1,
                            Categoria = "Caldos",
                            Nombre = "Caldo de Gallina",
                            Precio = 15.00m
                        },
                        new
                        {
                            PlatoId = 2,
                            Categoria = "Menu",
                            Nombre = "Arroz Chaufa",
                            Precio = 12.00m
                        },
                        new
                        {
                            PlatoId = 3,
                            Categoria = "Segundos",
                            Nombre = "Lomo Saltado",
                            Precio = 18.00m
                        });
                });

            modelBuilder.Entity("GastroPro.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Contrasena")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("GastroPro.Domain.Entities.Pago", b =>
                {
                    b.HasOne("GastroPro.Domain.Entities.CierreCaja", "CierreCaja")
                        .WithMany("Pagos")
                        .HasForeignKey("CierreCajaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CierreCaja");
                });

            modelBuilder.Entity("GastroPro.Domain.Entities.Pedido", b =>
                {
                    b.HasOne("GastroPro.Domain.Entities.Plato", "Plato")
                        .WithMany()
                        .HasForeignKey("PlatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plato");
                });

            modelBuilder.Entity("GastroPro.Domain.Entities.CierreCaja", b =>
                {
                    b.Navigation("Pagos");
                });
#pragma warning restore 612, 618
        }
    }
}
